apps/team/urls.py
# Import Django

from django.urls import path

# 

from .api import create_checkout_session, stripe_webhook
from .views import team, add, delete, edit, activate_team, invite, plans, plans_thankyou

#

app_name = 'team'

#

urlpatterns = [
    path('add/', add, name='add'),
    path('edit/', edit, name='edit'),
    path('invite/', invite, name='invite'),
    path('plans/', plans, name='plans'),
    path('plans/thank_you/', plans_thankyou, name='plans_thankyou'),
    path('activate_team/<int:team_id>/', activate_team, name='activate_team'),
    path('<int:team_id>/', team, name='team'),
    path('team/<str:id>/', delete, name='delete'),
    # API

    path('api/stripe_webhook/', stripe_webhook, name='stripe_webhook'),
    path('api/create_checkout_session/', create_checkout_session, name='create_checkout_session'),
]

apps/userprofile/urls.py
#
#

from django.urls import path


#
#

from .views import myaccount, edit_profile, accept_invitation, home

#
#

urlpatterns = [
    path('', myaccount, name='myaccount'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('accept_invitation/', accept_invitation, name='accept_invitation'),
]

minutos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from apps.core.views import frontpage, privacy, terms, plans, signup

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms, name='terms'),
    path('plans/', plans, name='plans'),
    path('admin/', admin.site.urls),


    #
    # Dashboard

    path('dashboard/', include('apps.dashboard.urls')),

    #
    # Auth

    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/models.py
# Import Django

from django.contrib.auth.models import User
from django.db import models

# Models

class Plan(models.Model):
    title = models.CharField(max_length=255)
    max_projects_per_team = models.IntegerField(default=0)
    max_members_per_team = models.IntegerField(default=0)
    max_tasks_per_project = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.title 

class Team(models.Model):
    #
    # Status

    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    #
    # Plan status

    PLAN_ACTIVE = 'active'
    PLAN_CANCELED = 'canceled'

    CHOICES_PLAN_STATUS = (
        (PLAN_ACTIVE, 'Active'),
        (PLAN_CANCELED, 'Canceled')
    )

    #
    # Fields

    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_teams', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    plan = models.ForeignKey(Plan, related_name='teams', on_delete=models.CASCADE, null=True )
    plan_end_date = models.DateTimeField(blank=True, null=True)
    plan_status = models.CharField(max_length=20, choices=CHOICES_PLAN_STATUS, default=PLAN_ACTIVE)
    stripe_customer_id = models.CharField(max_length=255, blank=True, null=True)
    stripe_subscription_id = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title

class Invitation(models.Model):
    #
    # Status

    INVITED = 'invited'
    ACCEPTED = 'accepted'

    CHOICES_STATUS = (
        (INVITED, 'Invited'),
        (ACCEPTED, 'Accepted')
    )

    team = models.ForeignKey(Team, related_name='invitations', on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

apps/userprofile/models.py
#
#

from django.contrib.auth.models import User
from django.db import models


#
# Models

class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    active_team_id = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='uploads/avatars/', blank=True, null=True)

    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return '/static/images/avatar.png'

apps/userprofile/views.py
#
#

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


#
# Import models

from .models import Userprofile
from apps.team.models import Team, Invitation
from apps.team.utilities import send_invitation_accepted


#
# Views
def home(request):
        return render(request, 'home.html')

@login_required
def myaccount(request):
    teams = request.user.teams.exclude(pk=request.user.userprofile.active_team_id)
    invitations = Invitation.objects.filter(email=request.user.email, status=Invitation.INVITED)

    return render(request, 'userprofile/myaccount.html', {'teams': teams, 'invitations': invitations})

@login_required
def edit_profile(request):
    if request.method == 'POST':
        request.user.first_name = request.POST.get('first_name', '')
        request.user.last_name = request.POST.get('last_name', '')
        request.user.email = request.POST.get('email', '')
        request.user.save()

        if request.FILES:
            avatar = request.FILES['avatar']
            userprofile = request.user.userprofile
            userprofile.avatar = avatar
            userprofile.save()

        messages.info(request, 'The changes was saved')

        return redirect('myaccount')
    
    return render(request, 'userprofile/edit_profile.html')

@login_required
def accept_invitation(request):
    if request.method == 'POST':
        code = request.POST.get('code')

        invitations = Invitation.objects.filter(code=code, email=request.user.email)

        if invitations:
            invitation = invitations[0]
            invitation.status = Invitation.ACCEPTED
            invitation.save()

            team = invitation.team
            team.members.add(request.user)
            team.save()

            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id
            userprofile.save()

            messages.info(request, 'Invitation accepted')

            send_invitation_accepted(team, invitation)

            return redirect('team:team', team_id=team.id)
        else:
            messages.info(request, 'Invitation was not found')
    else:
        return render(request, 'userprofile/accept_invitation.html')

apps/userprofile/templates/userprofile/accept_invitation.html
{% extends 'core/base.html' %}

{% block title %}Accept invitation | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Хяналтын самбар</a></li>
            <li><a href="{% url 'myaccount' %}">Аккаунт</a></li>
            <li class="is-active"><a href="{% url 'accept_invitation' %}" aria-current="page">Урилга хүлээн авах</a></li>
        </ul>
    </nav>
    <div style="width:1000px; height:400px; background-color:white; border-radius:15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; padding:40px; display:flex">

    <div class="columns">
        <div class="column is-4" style="width:400px">
            <h1 class="title">Урилга хүлээн авах</h1>

            <form method="post" action=".">
                {% csrf_token %}

                <div class="field">
                    <label>Нууц код (И-мэйлд ирсэн нууц код оруулна уу)</label>

                    <div class="control">
                        <input style="margin-top:10px; box-shadow: rgba(99, 99, 99, 0.2) 0px 5px 5px 0px; margin-bottom:10px" type="text" name="code" id="id_code" class="input is-rounded" placeholder="Нууц код">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-info is-rounded">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <img src="/media/uploads/avatars/welcome.avif" style="width:380px; height:340px; margin-left:150px; border-radius:15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; ">

    </div>
{% endblock %}

apps/userprofile/templates/userprofile/edit_profile.html
{% extends 'core/base.html' %}

{% block title %}Edit profile | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Хяналтын самбар</a></li>
            <li><a href="{% url 'myaccount' %}">Аккаунт</a></li>
            <li class="is-active"><a href="{% url 'edit_profile' %}" aria-current="page">Профайл засах</a></li>
        </ul>
    </nav>
<div style="background-color:white; height:100%; width:90%; border-radius:15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; padding:30px; display:flex " >   
    <div class="columns" >
        <div class="column is-4" style="width:350px; margin-left:50px">
            <h1 class="title">Профайл</h1>

            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="field">
                    <label>Нэр</label>

                    <div class="control">
                        <input type="text" placeholder="Нэр" name="first_name" id="first_name" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 5px 5px 0px;" class="input is-rounded"{% if request.user.first_name %} value="{{ request.user.first_name }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>Овог</label>

                    <div class="control">
                        <input type="text" placeholder="Овог" name="last_name" id="last_name" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 5px 5px 0px;" class="input is-rounded"{% if request.user.last_name %} value="{{ request.user.last_name }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>И-мэйл</label>

                    <div class="control">
                        <input type="text" placeholder="И-мэйл" name="email" id="email" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 5px 5px 0px;" class="input is-rounded"{% if request.user.email %} value="{{ request.user.email }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>Зураг</label>

                    <figure class="image is-64x64">
                        <img src="{{ request.user.userprofile.get_avatar }}" class="is-rounded" style=" box-shadow: rgba(99, 99, 99, 0.2) 0px 5px 5px 0px; ">
                    </figure>

                    <div class="control mt-2" >
                        <input type="file" name="avatar" id="id_avatar" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 5px 5px 0px; margin-top:25px" class="input is-rounded" >
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success" style="border-radius:15px; background-color:#41BEE7">Хадгалах</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <img src="/media/uploads/avatars/3d.avif" style="width:380px; height:480px; margin-left:150px; margin-top:10px; border-radius:15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; ">

</div>
{% endblock %}

apps/userprofile/templates/userprofile/myaccount.html
{% extends 'core/base.html' %}


{% block title %}My account | {% endblock %}

{% block content %}
{% load compress %}
{% load static%}
{% compress css %}
<link type="text/x-scss" rel="stylesheet" href="{% static 'css/button.scss' %}"/>
{% endcompress %}
<div style="width:100%">
    <nav class="breadcrumb" aria-label="breadcrumbs" style="margin-top:5px">
        <ul>
            <li><a href="#">Хяналтын самбар</a></li>
            <li class="is-active"><a href="{% url 'myaccount' %}" aria-current="page">Аккаунт</a></li>
        </ul>
    </nav>
    <div style="width:1000px; background-color:white; margin-bottom:30px; border-radius:15px; align-items:center; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;"> 

    <div class="columns" style="margin-left:5px">
        <div class="column is-6">
            <div class="media mb-4">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="{{ user.userprofile.get_avatar }}" class="is-rounded">
                    </figure>
                </div>

                <div class="media-content">
                    <p class="title is-3">{% firstof user.get_full_name user.username %}</p>
                    <p class="subtitle is-6">{{ user.email }}</p>
                </div>
            </div>

            <a href="{% url 'edit_profile' %}" class="button is-info" style="margin-top:10px; border-radius:15px; background-color:#41BEE7">
                <span class="icon"><i class="far fa-edit"></i></span>
                <span>Засах</span></a>
            <a href="{% url 'logout' %}" class="button is-danger " style="margin-top:10px; border-radius:15px">
                <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                <span>Гарах</span>
            </a>
        </div>
    </div>
</div>
<b style="font-size:20px; margin-left:5px">Хүсэлтүүд</b>
<div style="width:1000px; height:170px; background-color:white; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; margin-bottom:20px; border-radius:15px">
    {% if invitations %}
    <div class="card" style="width:100%; height:150px; margin-bottom:20px">
        <header class="card-header">
          <p class="card-header-title">
            Доорх "Team"-с хүсэлт ирсэн байна
          </p>
        </header>
        <footer class="card-footer">
        {% for invitation in invitations %}
          <a href="{% url 'accept_invitation' %}" class="card-footer-item" style="margin-top:10px">Манай "{{ invitation.team.title }}" ор</a>
        {% endfor %}

        </footer>
      </div>
    {% endif %}
</div>
<b style="font-size:20px; margin-left:5px;">Teams</b>
<div style="background-color:white; height:100%; width:1000px; padding:30px; border-radius:15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;">
    <div class="columns is-three-quarters-mobile"  style="display:block; ">    
        {% if active_team %}
            <div class="column is-4" style="width:800px;">
                <div class="notification has-background-success-light" style="border-radius:15px; background-color:#70CFEE; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;">
                    <h3 class="is-size-5">{{ active_team.title }}{% if active_team.created_by == request.user %}(Үүсгэгч){% else %}(Member){% endif %}</h3>
                
                    <h3 class="is-size-6">SHOW PLAN HERE</h3>

                    <hr>
                    <button class="learn-more">
                        <span class="circle" aria-hidden="true">
                          <span class="icon arrow"></span>
                        </span>
                        <a href="{% url 'team:team' active_team.id %}"><span class="button-text">Дэлгэрэнгүй</span></a>
                    </button>
                    {% if active_team.created_by == request.user %}
                        <!--<a href="#" class="button is-info">Invite users</a> -->
                    {% endif %}
                </div>
            </div>
        {% endif %}

        {% for team in teams %}
            <div class="column is-4" style="width:800px; border-radius:15px">
                <div class="notification" style="border-radius:15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;">
                    <h3 class="is-size-5">{{ team.title }}{% if team.created_by == request.user %}(Үүсгэсэн){% else %}(Гишүүн){% endif %}</h3>
                
                    <h3 class="is-size-6">SHOW PLAN HERE</h3>

                    <hr>
                    <button class="learn-more">
                        <span class="circle" aria-hidden="true">
                          <span class="icon arrow"></span>
                        </span>
                    <a href="{% url 'team:team' team.id %}"><span class="button-text">Дэлгэрэнгүй</span></a>
                    </button>
                    <div class="card" style="width:400px; margin-top:-50px; margin-left:250px; border-radius:30px;">
                        <footer class="card-footer">
                          <a href="{% url 'team:activate_team' team.id %}" class="card-footer-item" style="text-decoration:none">Идэвхижүүлэх</a>
                          <a href="{% url 'team:delete' team.id %}" class="card-footer-item" style="text-decoration:none">Устгах</a>
                        </footer>
                      </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>  
<div class="modal" >
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">Modal title</p>
        <button class="delete" aria-label="close"></button>
      </header>
      <section class="modal-card-body">
        <!-- Content ... -->
      </section>
      <footer class="modal-card-foot">
        <button class="button is-success">Save changes</button>
        <button class="button">Cancel</button>
      </footer>
    </div>
  </div>
  <script>
    const modalButton = document.getElementById('my-modal-button');
    const modal = document.querySelector('.modal');
    const closeModal = modal.querySelector('.modal-close');

    modalButton.addEventListener('click', function() {
      modal.classList.add('is-active');
    });
    
    closeModal.addEventListener('click', function() {
      modal.classList.remove('is-active');
    });
  </script>
{% endblock %}