apps/project/urls.py
#
# Import Django

from django.urls import path


#
# Import views

from .api import api_start_timer, api_stop_timer, api_discard_timer, api_get_tasks
from .views import projects, project, edit_project, task, edit_task, edit_entry, delete_entry, delete_untracked_entry, Charts, track_entry, Pdf


#
# Url pattern

app_name = 'project'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:project_id>/', project, name='project'),
    path('<int:project_id>/<int:task_id>/', task, name='task'),
    path('<int:project_id>/<int:task_id>/edit/', edit_task, name='edit_task'),
    path('<int:project_id>/<int:task_id>/<int:entry_id>/edit/', edit_entry, name='edit_entry'),
    path('<int:project_id>/<int:task_id>/<int:entry_id>/delete/', delete_entry, name='delete_entry'),
    path('<int:project_id>/edit/', edit_project, name='edit_project'),
    path('delete_untracked_entry/<int:entry_id>/', delete_untracked_entry, name='delete_untracked_entry'),
    path('track_entry/<int:entry_id>/', track_entry, name='track_entry'),
    path('project/<str:id>/gantt', Charts, name='chart'),
    path('<int:project_id>/<int:task_id>/DownloadData/', Pdf, name='DownloadData'),
    # API

    path('api/start_timer/', api_start_timer, name='api_start_timer'),
    path('api/stop_timer/', api_stop_timer, name='api_stop_timer'),
    path('api/discard_timer/', api_discard_timer, name='api_discard_timer'),
    path('api/get_tasks/', api_get_tasks, name='api_get_tasks'),

]

minutos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from apps.core.views import frontpage, privacy, terms, plans, signup

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms, name='terms'),
    path('plans/', plans, name='plans'),
    path('admin/', admin.site.urls),


    #
    # Dashboard

    path('dashboard/', include('apps.dashboard.urls')),

    #
    # Auth

    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/project/models.py
#
# Import Django

from django.contrib.auth.models import User
from django.db import models


#
# Import models

from apps.team.models import Team


#
# Models

class Project(models.Model):
    team = models.ForeignKey(Team, related_name='projects', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)

    created_by = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title
    
    def registered_time(self):
        return sum(entry.minutes for entry in self.entries.all())
    
    def num_tasks_Todo(self):
        return self.tasks.filter(status=Task.Todo).count()

class Task(models.Model):
    #
    # Status choices

    Todo = 'Todo'
    DONE = 'done'
    ARCHIVED = 'archived'

    CHOICES_STATUS = (
        (Todo, 'Todo'),
        (DONE, 'Done'),
        (ARCHIVED, 'Archived')
    )

    team = models.ForeignKey(Team, related_name='tasks', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    task_startdate = models.DateField(null=True)
    task_enddate = models.DateField(null=True)
    file = models.FileField(upload_to='uploads/', null=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=Todo)

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.title
    
    def registered_time(self):
        return sum(entry.minutes for entry in self.entries.all())

class Entry(models.Model):
    team = models.ForeignKey(Team, related_name='entries', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    task = models.ForeignKey(Task, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    minutes = models.IntegerField(default=0)
    is_tracked = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='entries', on_delete=models.CASCADE)
    created_at = models.DateTimeField()

    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        if self.task:
            return '%s - %s' % (self.task.title, self.created_at)
        
        return '%s' % self.created_at

apps/project/views.py
#
# Import Python

from datetime import datetime


#
# Import Django
from django.http import FileResponse 
from reportlab.pdfgen import canvas  
from reportlab.lib.units import inch 
from reportlab.lib.pagesizes import letter  
from reportlab.platypus import Table 
from reportlab.lib import colors
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
import plotly.graph_objects as go
import pandas as pd
from plotly.offline import plot
import plotly.express as px
import plotly.offline as pyo
from dash import html
import dash

#
# Import models

from .models import Project, Task, Entry
from apps.team.models import Team



#
# View

@login_required
def projects(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    projects = team.projects.all()

    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            project = Project.objects.create(team=team, title=title, created_by=request.user)

            messages.info(request, 'The project was added!')

            return redirect('project:projects')

    return render(request, 'project/projects.html', {'team': team, 'projects': projects})

@login_required
def project(request, project_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == 'POST':
        title = request.POST.get('title')
        task_startdate = request.POST.get('task_startdate')
        task_enddate = request.POST.get('task_enddate')
        file = request.POST.get('file')

        if title:
            task = Task.objects.create(team=team, project=project, created_by=request.user, title=title, task_startdate=task_startdate, task_enddate=task_enddate, file=file)

            messages.info(request, 'The task was added!')

            return redirect('project:project', project_id=project.id)
    
    tasks_Todo = project.tasks.filter(status=Task.Todo)
    tasks_done = project.tasks.filter(status=Task.DONE)

    return render(request, 'project/project.html', {'team': team, 'project': project, 'tasks_Todo': tasks_Todo, 'tasks_done': tasks_done})

@login_required
def edit_project(request, project_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == 'POST':
        title = request.POST.get('title')

        if title:
            project.title = title
            project.save()

            messages.info(request, 'Амжилттай хадгаллаа')

            return redirect('project:project', project_id=project.id)
    
    return render(request, 'project/edit_project.html', {'team': team, 'project': project})

@login_required
def task(request, project_id, task_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        date = '%s %s' % (request.POST.get('date'), datetime.now().time())
        minutes_total = (hours * 60) + minutes
        entry = Entry.objects.create(team=team, project=project, task=task, minutes=minutes_total, created_by=request.user, created_at=date, is_tracked=True)

       
    return render(request, 'project/task.html', {'today': datetime.today(), 'team': team, 'project': project, 'task': task})

@login_required
def edit_task(request, project_id, task_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    if request.method == 'POST':
        title = request.POST.get('title')
        status = request.POST.get('status')
        task_startdate = request.POST.get('task_startdate')
        task_enddate = request.POST.get('task_enddate')

        if title:
            task.title = title
            task.status = status
            task.task_startdate = task_startdate
            task.task_enddate = task_enddate
            task.save()

            messages.info(request, 'The changes was saved!')

            return redirect('project:task', project_id=project.id, task_id=task.id)

    return render(request, 'project/edit_task.html', {'team': team, 'project': project, 'task': task})

@login_required
def edit_entry(request, project_id, task_id, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))

        date = '%s %s' % (request.POST.get('date'), datetime.now().time())

        entry.created_at = date
        entry.minutes = (hours * 60) + minutes
        entry.save()

        messages.info(request, 'The changes was saved!')

        return redirect('project:task', project_id=project.id, task_id=task.id)
    
    hours, minutes = divmod(entry.minutes, 60)
    
    context = {
        'team': team,
        'project': project,
        'task': task,
        'entry': entry,
        'hours': hours,
        'minutes': minutes
    }
    
    return render(request, 'project/edit_entry.html', context)

@login_required
def delete_entry(request, project_id, task_id, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    entry.delete()

    messages.info(request, 'The entry was deleted!')

    return redirect('project:task', project_id=project.id, task_id=task.id)

@login_required
def delete_untracked_entry(request, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    entry.delete()

    messages.info(request, 'The entry was deleted!')

    return redirect('dashboard')

@login_required
def track_entry(request, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    projects = team.projects.all()

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        project = request.POST.get('project')
        task = request.POST.get('task')

        if project and task:
            entry.project_id = project
            entry.task_id = task
            entry.minutes = (hours * 60) + minutes
            entry.created_at = '%s %s' % (request.POST.get('date'), entry.created_at.time())
            entry.is_tracked = True
            entry.save()

            messages.info(request, 'The time was tracked')

            return redirect('dashboard')
    
    hours, minutes = divmod(entry.minutes, 60)

    context = {
        'hours': hours,
        'minutes': minutes,
        'team': team,
        'projects': projects,
        'entry': entry
    }

    return render(request, 'project/track_entry.html', context)


def Charts(request, id):

    proj = Project.objects.get(id = id)
    tasks = Task.objects.filter(project = proj)
    fig = go.Figure(data=go.Scatter(x=[1, 3, 2], y=[4,5,6]))
    projects_data = [
        {
            'Task': id,
            'Start': x.task_startdate,
            'Finish': x.task_enddate,
            'Task': x.title
        } for x in tasks
    ]
    df = pd.DataFrame(projects_data)
    fig = px.timeline(
        df, x_start="Start", x_end="Finish", y="Task", color="Task", width=1000, height=400
    )
    layout = {
        "margin": {"l": 1, "r": 1, "t": 50, "b": 50},
        "width": 1000,
        "height": 500,
        "autosize": False,
        "paper_bgcolor": "rgba(0,0,0,0)",
    }

    fig.update_layout(
        layout,
        yaxis=dict(showgrid=True),
        xaxis=dict(showgrid=False),
    )
    fig.update_yaxes(autorange="reversed")
    fig.update_traces(width=0.2)
    gantt_plot = plot(fig, output_type="div")
    context = {'plot_div': gantt_plot, 'task': tasks }
    return render(request, 'Gantt/base.html', context)

def Pdf(request, project_id, task_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    task_id = request.GET.get('task_id').strip()

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="taskData.pdf"'


    image_path = 'static/images/index.jpg' 
    result = Task.objects.filter(id=task_id)

    for fields in result:
         team = fields.team
         project = fields.project
         title = fields.title                                                                                                        
         created_by = fields.created_by
         created_at = fields.created_at
         task_startdate = fields.task_startdate
         task_enddate = fields.task_enddate
         status = fields.status


    p = canvas.Canvas(response, pagesize=letter)

apps/project/templates/project/edit_task.html
{% extends 'core/base.html' %}

{% block title %}Edit task | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Хяналтын самбар</a></li>
                <li><a href="{% url 'project:projects' %}">Төслүүп</a></li>
                <li><a href="{% url 'project:project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'project:edit_task' project.id task.id %}" aria-current="page">Даалгавар засах</a></li>
            </ul>
        </nav>
        <div style="width:1000px; height:550px; background-color:white; border-radius:15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; padding:40px; ">

        <div class="columns">
            <div class="column">
                <h1 class="title">Даалгавар засах</h1>
            </div>
        </div>

        <div class="columns">
            <div class="column is-4">
                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="field">
                        <label>Нэр</label>

                        <div class="control">
                            <input type="text" name="title" id="id_title" class="input" value="{{ task.title }}">
                        </div>
                        <label>Эхлэх хугацаа</label>
                        <div class="field">
                            <input type="date" name="task_startdate" id="id_task_startdate" class="input" value="{{ task.task_startdate}}">
                        </div> 
                        <label>Дуусах хугацаа</label>
                        <div class="field">
                            <input type="date" name="task_enddate" id="id_task_enddate" class="input" value="{{task.task_enddate}}">
                        </div>
                        <label>Файл</label>
                        <div class="field">
                            <input type="file" name="file" id="id_file" class="input" value="{{task.file}}">
                        </div>
                    </div>

                    <div class="field">
                        <label>Статус</label>

                        <div class="control">
                            <div class="select">
                                <select name="status" id="id_status">
                                    <option value="Todo"{% if task.status == 'Todo' %} selected{% endif %}>Шинэ</option>
                                    <option value="done"{% if task.status == 'done' %} selected{% endif %}>Дууссан</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <button class="button is-info">Хадгалах</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

apps/project/templates/project/project.html
{% extends 'core/base.html' %}

{% block title %}{{ project.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Хяналтын самбар</a></li>
                <li><a href="{% url 'project:projects' %}">Төслүүд</a></li>
                <li class="is-active"><a href="{% url 'project:project' project.id %}" aria-current="page">{{ project.title }}</a></li>
            </ul>
        </nav>

        <div class="columns">
            <div class="column">
                <h1 class="title">{{ project.title }}</h1>

                <div class="buttons">
                    <a @click="showAddTaskModal = !showAddTaskModal" title="Даалгавар нэмэх" class="button is-link is-focused is-active">Даалгавар нэмэх</a>
                    <a href="{% url 'project:edit_project' project.id %}" title="Төсөл засах" class="button is-info is-active">Төсөл засах</a>
                    <a href="{% url 'project:chart' project.id %}" title="Гантт чарт" class="button is-primary is-active">Ганнт чарт</a>
                    <a href="#" class="button is-primary" title="Тун удахгүй" disabled>Board view</a>
                </div>
            </div>
        </div>

        {% if not tasks_Todo and not tasks_done %}
            <div class="columns">
                <div class="column is-3">
                    <div class="notification">
                        <p>Даалгавар байхгүй байна</p>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="columns is-multiline" style="">
            {% if tasks_Todo %}
                <div class="column is-12">
                    <h2 class="is-size-4">Шинэ</h2>
                </div>

                {% for task in tasks_Todo %}
                    <div class="column is-4">
                        <div class="notification" style="background-color:white; margin-right:25px; border-radius:15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;">
                            <h3 class="is-size-5">{{ task.title }}</h3>

                            <p>Registered time: {{ task.registered_time }}</p>

                            <hr>

                            <a href="{% url 'project:task' project.id task.id %}" class="button is-link is-light">Дэлгэрэнгүй</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% if tasks_done %}
                <div class="column is-12">
                    <h2 class="is-size-4">Дууссан</h2>
                </div>

                {% for task in tasks_done %}
                    <div class="column is-4">
                        <div class="notification" style="background-color:white; border-radius:15px; margin-right:20px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;">
                            <h3 class="is-size-5">{{ task.title }}</h3>

                            <p>Registered time: {{ task.registered_time }}</p>

                            <hr>

                            <a href="{% url 'project:task' project.id task.id %}" class="button is-link">Дэлгэрэнгүй</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div class="modal" :class="{'is-active': showAddTaskModal }">
            <div class="modal-background"></div>

            <form method="POST" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="modal-card">
                    <div class="modal-card-head">
                        <p class="modal-card-title ">Даалгавар нэмэх</p>
                    </div>

                    <div class="modal-card-body">
                        <div class="field">
                            <label>Нэр</label>
                            <div class="control">
                                <input placeholder="Enter your task name" type="text" name="title" id="id_title" v-model="title" class="input">
                            </div>
                        </div>
                        <div class="field">
                            <label>Эхлэх хугацаа</label>
                            <div class="control">
                                <input type="date" name="task_startdate" id="id_task_startdate" v-model="task_startdate" class="input">
                            </div> 
                        </div>
                        <div>
                            <label>Дуусах хугацаа</label>
                            <div class="control">
                                <input type="date" name="task_enddate" id="id_task_enddate" v-model="task_enddate" class="input">
                            </div>
                        </div>
                        <div>
                            <label>Файл</label>
                            <div class="control">
                                <input type="file" name="file" id="id_file" v-model="file" class="input">
                            </div>
                        </div>
                        <div class="notification is-danger" v-if="showError">
                            Нэрээ оруулна уу!
                        </div>
                    </div>

                    <footer class="modal-card-foot">
                        <button class="button is-info">Хадгалах</button>
                        <button class="button is-info is-outlined" @click="showAddTaskModal = !showAddTaskModal">Болих</button>
                    </footer>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const ProjectApp = {
            data() {
                return {
                    showAddTaskModal: false,
                    title: '',
                    showError: false
                }
            },
            delimiters: ['[[', ']]'],
            methods: {
                validateForm(e) {
                    if (this.title) {
                        return true
                    }

                    this.showError = true

                    e.preventDefault()

                    return false
                }
            }
        }

        Vue.createApp(ProjectApp).mount('#project-app')
    </script>
{% endblock %}

apps/project/templates/project/task.html
{% extends 'core/base.html' %}

{% load dashboardextras %}

{% block title %}{{ task.title }} | {% endblock %}

{% block content %}
    <div id="project-app">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Хяналтын самбар</a></li>
                <li><a href="{% url 'project:projects' %}">Төслүүд</a></li>
                <li><a href="{% url 'project:project' project.id %}">{{ project.title }}</a></li>
                <li class="is-active"><a href="{% url 'project:task' project.id task.id %}" aria-current="page">{{ task.title }}</a></li>
            </ul>
        </nav>
        <div style="background-color:white; height:100%; padding:50px; border-radius:15px; margin-right:60px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;">
            <div class="columns" style="display:flex">
                <div class="column">
                    <h1 class="title">{{ task.title }} ({{ task.get_status_display }})</h1>
                    <span class="tag is-link is-light">{{task.task_startdate}}</span>
                    <span class="tag is-link is-light">{{task.task_enddate}}</span> <br>
                    <a href="{% url 'project:edit_task' project.id task.id %}" class="button is-info" style="margin-top:30px">Засах</a>
                    <a href="DownloadData/?task_id={{task.id}}" class="button is-info" style="margin-top:30px">Хэвлэх</a>

                    <!--<a href="#">{{ task.file }}</a> -->
                    <h2 class="subtitle mt-6">Цаг оруулах</h2>

                    <form method="post" action=".">
                        {% csrf_token %}

                        <div class="field is-grouped">
                            <div class="control">
                                <div class="select">
                                    <select name="hours">
                                        <option value="0">0цаг</option>
                                        {% for i in "x"|rjust:"10" %}
                                            <option value="{{ forloop.counter }}">{{ forloop.counter }}цаг</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div class="control">
                                <div class="select">
                                    <select name="minutes">
                                        <option value="0">0мин</option>
                                        {% for i in "x"|rjust:"59" %}
                                            <option value="{{ forloop.counter }}">{{ forloop.counter }}m</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="field">
                            <label>Он сар</label>

                            <div class="control">
                                <input type="date" id="id_date" name="date" class="input" style="width:400px" value="{{ today|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
                            </div>
                        </div>
                        <div class="field">
                            <div class="control">
                                <button class="button is-link">Submit</button>
                            </div>
                        </div>
                        
                    </form>
                </div>
                <img src="/media/uploads/avatars/project.jpg" style="width:500px; height:400px; margin-top:40px; border-radius:15px; margin-right:20px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; ">

            </div>

            <div class="columns">
                <div class="column is-12 is-rounded">
                    <hr>

                    <h2 class="subtitle">Зарцуулсан хугацаа</h2>

                    {% if task.entries.all %}
                        <table class="table is-fullwidth" style="text-align: left;">
                            <thead>
                                <tr style="background-color:#41BEE7;">
                                    <th style="color:white">Он сар</th>
                                    <th style="color:white">Хэрэглэгч</th>
                                    <th style="color:white">Time</th>
                                    <th style="color:white"></th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for entry in task.entries.all %}
                                    <tr>
                                        <td>{{ entry.created_at }}</td>
                                        <td><a class="button is-link is-light" style="margin-bottom:10px; margin-top:10px">{% firstof entry.created_by.get_full_name entry.created_by.username %}</a></td>
                                        <td>{{ entry.minutes|format_minutes }}</td>
                                        <td>
                                            <a class="button is-link is-outlined" href="{% url 'project:edit_entry' project.id task.id entry.id %}">Засах</a>
                                            <a class="button is-danger is-outlined" href="{% url 'project:delete_entry' project.id task.id entry.id %}">Устгах</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>

                            <tfoot>
                                <tr>
                                    <th colspan="2">Нийт</th>
                                    <th colspan="2">{{ task.registered_time|format_minutes }}</th>
                                </tr>
                            </tfoot>
                        </table>
                    {% else %}
                        <p>No entries yet...</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}