apps/dashboard/urls.py
# Import Django

from django.urls import path, include

# Import Views

from .views import dashboard, view_user

#

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('<int:user_id>/', view_user, name='view_user'),
    path('projects/', include('apps.project.urls')),

    path('myaccount/', include('apps.userprofile.urls')),
    path('myaccount/teams/', include('apps.team.urls')),
]

apps/project/urls.py
#
# Import Django

from django.urls import path


#
# Import views

from .api import api_start_timer, api_stop_timer, api_discard_timer, api_get_tasks
from .views import projects, project, edit_project, task, edit_task, edit_entry, delete_entry, delete_untracked_entry, Charts, track_entry, Pdf


#
# Url pattern

app_name = 'project'

urlpatterns = [
    path('', projects, name='projects'),
    path('<int:project_id>/', project, name='project'),
    path('<int:project_id>/<int:task_id>/', task, name='task'),
    path('<int:project_id>/<int:task_id>/edit/', edit_task, name='edit_task'),
    path('<int:project_id>/<int:task_id>/<int:entry_id>/edit/', edit_entry, name='edit_entry'),
    path('<int:project_id>/<int:task_id>/<int:entry_id>/delete/', delete_entry, name='delete_entry'),
    path('<int:project_id>/edit/', edit_project, name='edit_project'),
    path('delete_untracked_entry/<int:entry_id>/', delete_untracked_entry, name='delete_untracked_entry'),
    path('track_entry/<int:entry_id>/', track_entry, name='track_entry'),
    path('project/<str:id>/gantt', Charts, name='chart'),
    path('<int:project_id>/<int:task_id>/DownloadData/', Pdf, name='DownloadData'),
    # API

    path('api/start_timer/', api_start_timer, name='api_start_timer'),
    path('api/stop_timer/', api_stop_timer, name='api_stop_timer'),
    path('api/discard_timer/', api_discard_timer, name='api_discard_timer'),
    path('api/get_tasks/', api_get_tasks, name='api_get_tasks'),

]

minutos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from apps.core.views import frontpage, privacy, terms, plans, signup

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms, name='terms'),
    path('plans/', plans, name='plans'),
    path('admin/', admin.site.urls),


    #
    # Dashboard

    path('dashboard/', include('apps.dashboard.urls')),

    #
    # Auth

    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/dashboard/views.py
# Import Python

from datetime import datetime, timedelta, timezone
from dateutil.relativedelta import relativedelta

# Import Django

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

# Import models

from apps.project.models import Entry
from apps.team.models import Team

# Import utilities

from .utilities import get_time_for_user_and_date, get_time_for_team_and_month, get_time_for_user_and_month, get_time_for_user_and_project_and_month, get_time_for_user_and_team_month

# Views

@login_required
def dashboard(request):
    # Check if active team

    if not request.user.userprofile.active_team_id:
        return redirect('myaccount')
    
    # Get team and set variable

    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    all_projects = team.projects.all()
    members = team.members.all()

    # User date, pagination

    num_days = int(request.GET.get('num_days', 0))
    date_user = datetime.now() - timedelta(days=num_days)

    date_entries = Entry.objects.filter(team=team, created_by=request.user, created_at__date=date_user, is_tracked=True)
    
    # User month, pagination

    user_num_months = int(request.GET.get('user_num_months', 0))
    user_month = datetime.now()-relativedelta(months=user_num_months)

    for project in all_projects:
        project.time_for_user_and_project_and_month = get_time_for_user_and_project_and_month(team, project, request.user, user_month)
    
    # Team month, pagination

    team_num_months  = int(request.GET.get('team_num_months', 0))
    team_month = datetime.now()-relativedelta(months=team_num_months)

    for member in members:
        member.time_for_user_and_team_and_month = get_time_for_user_and_team_month(team, member, team_month)

    #

    untracked_entries = Entry.objects.filter(team=team, created_by=request.user, is_tracked=False).order_by('-created_at')

    for untracked_entry in untracked_entries:
        untracked_entry.minutes_since = int((datetime.now(timezone.utc) - untracked_entry.created_at).total_seconds() / 60)

    # Context

    context = {
        'team': team,
        'all_projects': all_projects,
        'projects': all_projects[0:4],
        'date_entries': date_entries,
        'num_days': num_days,
        'date_user': date_user,
        'members': members,
        'untracked_entries': untracked_entries,
        'user_num_months': user_num_months,
        'user_month': user_month,
        'time_for_user_and_month': get_time_for_user_and_month(team, request.user, user_month),
        'time_for_user_and_date': get_time_for_user_and_date(team, request.user, date_user),
        'time_for_team_and_month': get_time_for_team_and_month(team, team_month),
        'team_num_months': team_num_months,
        'team_month': team_month
    }

    return render(request, 'dashboard/dashboard.html', context)

@login_required
def view_user(request, user_id):
    # Get team, user and set variables

    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    all_projects = team.projects.all()
    user = team.members.all().get(id=user_id)

    # User date, pagination

    num_days = int(request.GET.get('num_days', 0))
    date_user = datetime.now() - timedelta(days=num_days)

    date_entries = Entry.objects.filter(team=team, created_by=request.user, created_at__date=date_user, is_tracked=True)
    
    # User month, pagination

    user_num_months = int(request.GET.get('user_num_months', 0))
    user_month = datetime.now()-relativedelta(months=user_num_months)

    for project in all_projects:
        project.time_for_user_and_project_and_month = get_time_for_user_and_project_and_month(team, project, request.user, user_month)

    # Context

    context = {
        'team': team,
        'all_projects': all_projects,
        'date_entries': date_entries,
        'num_days': num_days,
        'date_user': date_user,
        'user_num_months': user_num_months,
        'user_month': user_month,
        'time_for_user_and_month': get_time_for_user_and_month(team, request.user, user_month),
        'time_for_user_and_date': get_time_for_user_and_date(team, request.user, date_user),
    }

    return render(request, 'dashboard/view_user.html', context)

apps/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% load dashboardextras %}

{% block title %}Dashboard | {% endblock %}

{% block content %}
    <div class="columns is-multiline">
        <div class="column is-6">
            <div class="notification" style="background-color:white; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; border-radius:15px ">
                <h2 class="subtitle">Таны цаг {% if num_days is 0 %}өнөөдрийн{% else %}{{ date_user|date:"Y-m-d" }}{% endif %}</h2>
            
                {% if date_entries %}
                    <table class="table is-fullwidth" style="text-align: left;">
                        <thead>
                            <tr style="background-color:#41BEE7;">
                                <th style="color:white">Даалгавар</th>
                                <th style="color:white">Төсөл</th>
                                <th style="color:white">Цаг</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for entry in date_entries %}
                            <tr>
                                <td>{{ entry.task.title }}</td>
                                <td>{{ entry.project.title }}</td>
                                <td>{{ entry.minutes|format_minutes }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>

                        <tfoot>
                            <tr>
                                <td colspan="2">Нийт</td>
                                <td>{{ time_for_user_and_date|format_minutes }}</td>
                            </tr>
                        </tfoot>
                    </table>
                {% else %}
                    <p class="block">No entries today...</p>
                {% endif %}

                <a href="?num_days={{ num_days|add:'1' }}" class="button is-link is-inverted">Өмнөх</a>
                {% if num_days > 0 %}
                <a href="?num_days={{ num_days|add:'-1' }}" class="button is-link is-inverted">Дараагийн</a>
                {% endif %}
            </div>
        </div>

        <div class="column is-6">
            <div class="notification" style="background-color:white; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; border-radius:15px">
                <h2 class="subtitle">Таны цаг {% if user_num_months is 0 %}энэ сард{% else %}{{ user_month|date:"Y-m" }}{% endif %}</h2>
            
                {% if time_for_user_and_month %}
                    <table class="table is-fullwidth" style="text-align: left;">
                        <thead>
                            <tr style="background-color:#41BEE7">
                                <th style="color:white">Төсөл</th>
                                <th style="color:white">Цаг</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for project in all_projects %}
                                {% if project.time_for_user_and_project_and_month > 0 %}
                                <tr>
                                    <td>{{ project.title }}</td>
                                    <td>{{ project.time_for_user_and_project_and_month|format_minutes }}</td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>

                        <tfoot>
                            <tr>
                                <td>Нийт</td>
                                <td>{{ time_for_user_and_month|format_minutes }}</td>
                            </tr>
                        </tfoot>
                    </table>
                {% else %}
                    <p class="block">No entries this month...</p>
                {% endif %}

                <a href="?user_num_months={{ user_num_months|add:'1' }}" class="button is-link is-inverted">Өмнөх</a>
                {% if user_num_months > 0 %}
                <a href="?user_num_months={{ user_num_months|add:'-1' }}" class="button is-link is-inverted">Дараагийн</a>
                {% endif %}
            </div>
        </div>

        <div class="column is-6">
            <div class="notification" style="background-color:white; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; border-radius:15px">
                <h2 class="subtitle">Your untracked entries</h2>

                <table class="table is-fullwidth" style="text-align: left;">
                    <thead>
                        <tr style="background-color:#41BEE7;">
                            <th style="color:white">Эхэлсэн</th>
                            <th style="color:white">Цаг</th>
                            <th style="color:white">Статус</th>
                            <th style="color:white">Нэмэх</th>
                            <th style="color:white">Устгах</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for entry in untracked_entries %}
                            <tr>
                                <td>{{ entry.created_at }}</td>
                                <td>
                                    {% if entry.minutes == 0 %}
                                        {{ entry.minutes_since|format_minutes }}
                                    {% else %}
                                        {{ entry.minutes|format_minutes }}
                                    {% endif %}
                                </td>
                                <td>{% if entry.minutes == 0 %}In progress{% else %}Untracked{% endif %}</td>
                                <td><a href="{% url 'project:track_entry' entry.id %}" style="text-decoration:none;" class="button is-link is-outlined">Нэмэх</a></td>
                                <td><a href="{% url 'project:delete_untracked_entry' entry.id %}" class="button is-danger is-outlined">Устгах</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        {% if request.user == team.created_by %}
            <div class="column is-6">
                <div class="notification" style="background-color:white; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;border-radius:15px">
                    <h2 class="subtitle">Таны баг {% if team_num_months is 0 %}энэ сард{% else %}{{ team_month|date:"Y-m" }}{% endif %}</h2>
                
                    {% if time_for_team_and_month > 0 %}
                        <table class="table is-fullwidth" style="text-align: left;">
                            <thead>
                                <tr style="background-color:#41BEE7">
                                    <th style="color:white">Нэр</th>
                                    <th style="color:white">Цаг</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for member in members %}
                                    <tr>
                                        <td><a href="{% url 'view_user' member.id %}" class="button is-link is-light">{% firstof member.get_full_name member.username %}</a></td>
                                        <td>{{ member.time_for_user_and_team_and_month|format_minutes }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>No registred time for your team this month...</p>
                    {% endif %}

                    <a href="?team_num_months={{ team_num_months|add:'1' }}" class="button is-link is-inverted">Өмнөх</a>
                    {% if team_num_months > 0 %}
                    <a href="?team_num_months={{ team_num_months|add:'-1' }}" class="button is-link is-inverted">Дараагийн</a>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>

    <div class="columns is-multiline" >
        <div class="column is-12">
            <h2 class="subtitle">Шинэ төслүүд</h2>
        </div>

        {% for project in projects %}
            <div class="column is-3">
                <div class="notification" style="background-color:white; box-shadow: 3px 3px 3px 3px rgba(1,1,1,.05); border-radius:15px">
                    <h2 class="is-size-5">{{ project.title }}</h2>

                    <p class="is-size-7">Registered time: {{ project.registered_time|format_minutes }}</p>
                    <p class="is-size-7">Tasks: {{ project.num_tasks_Todo }}</p>

                    <hr>

                    <a href="{% url 'project:project' project.id %}" class="button is-info">Дэлгэрэнгүй</a>
                </div>
            </div>
        {% empty %}
            <div class="column is-3">
                <div class="notification">
                    <p>No projects yet...</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

apps/dashboard/templates/dashboard/view_user.html
{% extends 'core/base.html' %}

{% load dashboardextras %}

{% block title %}{% firstof user.get_full_name user.username %} | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Хяналтын самбар</a></li>
            <li class="is-active"><a href="{% url 'view_user' user.id %}" aria-current="page">{% firstof user.get_full_name user.username %}</a></li>
        </ul>
    </nav>
    
    <div class="columns is-multiline">
        <div style="width:1130px; height:100%; background-color:white; border-radius:15px; padding:10px; margin-left:10px; margin-bottom:20px; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;"> 
            <div class="column is-12">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-64x64" style="margin-bottom:20px;"> 
                            <img style="border-radius:5px" src="{{ user.userprofile.get_avatar }}">
                        </figure>
                    </div>

                    <div class="media-content">
                        <p class="title is-3">{% firstof user.get_full_name user.username %}</p>
                        <p class="subtitle is-6">{{ user.email }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="column is-6">
            <div class="notification" style="background-color:white; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px; border-radius:15px">
                <h2 class="subtitle">{% firstof user.get_full_name user.username %}'s time {% if num_days is 0 %}today{% else %}{{ date_user|date:"Y-m-d" }}{% endif %}</h2>
            
                {% if date_entries %}
                    <table class="table is-fullwidth" style="text-align: left;">
                        <thead>
                            <tr style="background-color:#41BEE7">
                                <td>Task</td>
                                <td>Project</td>
                                <td>Time</td>
                            </tr>
                        </thead>

                        <tbody>
                            {% for entry in date_entries %}
                            <tr>
                                <td>{{ entry.task.title }}</td>
                                <td>{{ entry.project.title }}</td>
                                <td>{{ entry.minutes|format_minutes }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>

                        <tfoot>
                            <tr>
                                <td colspan="2">Нийт</td>
                                <td>{{ time_for_user_and_date|format_minutes }}</td>
                            </tr>
                        </tfoot>
                    </table>
                {% else %}
                    <p class="block">No entries today...</p>
                {% endif %}

                <a href="?num_days={{ num_days|add:'1' }}" class="button is-link is-inverted">Өмнөх</a>
                {% if num_days > 0 %}
                <a href="?num_days={{ num_days|add:'-1' }}" class="button is-link is-inverted">Дараагийн</a>
                {% endif %}
            </div>
        </div>

        <div class="column is-6">
            <div class="notification" style="background-color:white; box-shadow: rgba(99, 99, 99, 0.2) 0px 10px 10px 0px;border-radius:15px; margin-right:40px">
                <h2 class="subtitle">{% firstof user.get_full_name user.username %}'s time {% if user_num_months is 0 %}this month{% else %}{{ user_month|date:"Y-m" }}{% endif %}</h2>
            
                {% if time_for_user_and_month %}
                    <table class="table is-fullwidth" style="text-align: left;">
                        <thead>
                            <tr style="background-color:#41BEE7">
                                <td>Project</td>
                                <td>Time</td>
                            </tr>
                        </thead>

                        <tbody>
                            {% for project in all_projects %}
                                {% if project.time_for_user_and_project_and_month > 0 %}
                                <tr>
                                    <td>{{ project.title }}</td>
                                    <td>{{ project.time_for_user_and_project_and_month|format_minutes }}</td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>

                        <tfoot>
                            <tr>
                                <td>Нийт</td>
                                <td>{{ time_for_user_and_month|format_minutes }}</td>
                            </tr>
                        </tfoot>
                    </table>
                {% else %}
                    <p class="block">No entries this month...</p>
                {% endif %}

                <a href="?user_num_months={{ user_num_months|add:'1' }}" class="button is-link is-inverted">Өмнөх</a>
                {% if user_num_months > 0 %}
                <a href="?user_num_months={{ user_num_months|add:'-1' }}" class="button is-link is-inverted">Дараагийн</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}